#!/bin/bash
# =============================================================================
#  DotFiles Installer — Arch Linux
#  Instala e configura: kitty, starship, zsh, oh-my-zsh e mirrorlist
# =============================================================================

set -e  # Para o script se der qualquer erro

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "╔══════════════════════════════════════╗"
echo "║     DotFiles Installer iniciando     ║"
echo "╚══════════════════════════════════════╝"
echo ""

# =============================================================================
# 1. MIRRORLIST
# =============================================================================
echo ">>> [1/6] Atualizando mirrorlist..."

sudo tee /etc/pacman.d/mirrorlist > /dev/null << 'EOF'
################################################################################
################# Arch Linux mirrorlist generated by Reflector #################
################################################################################
Server = http://br.mirrors.cicku.me/archlinux/$repo/os/$arch
Server = https://br.mirrors.cicku.me/archlinux/$repo/os/$arch
Server = https://mirror.ufscar.br/archlinux/$repo/os/$arch
Server = http://mirror.ufscar.br/archlinux/$repo/os/$arch
Server = https://archlinux.c3sl.ufpr.br/$repo/os/$arch
Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch
Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch
EOF

echo "    Mirrorlist atualizado!"

# =============================================================================
# 2. ATUALIZAR SISTEMA E INSTALAR PACOTES
# =============================================================================
echo ""
echo ">>> [2/6] Atualizando pacotes e instalando dependências..."

sudo pacman -Syy --noconfirm
sudo pacman -S --noconfirm --needed \
    unzip \
    kitty \
    starship \
    zsh \
    curl \
    git \
    fastfetch

echo "    Pacotes instalados!"

# =============================================================================
# 3. OH-MY-ZSH + PLUGINS
# =============================================================================
echo ""
echo ">>> [3/6] Instalando Oh My Zsh e plugins..."

# Instala oh-my-zsh se ainda não estiver instalado
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    RUNZSH=no CHSH=no sh -c \
        "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    echo "    Oh My Zsh instalado!"
else
    echo "    Oh My Zsh já está instalado, pulando..."
fi

ZSH_CUSTOM="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"

# zsh-autosuggestions
if [ ! -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions \
        "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
fi

# zsh-syntax-highlighting
if [ ! -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting \
        "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
fi

# zsh-completions
if [ ! -d "$ZSH_CUSTOM/plugins/zsh-completions" ]; then
    git clone https://github.com/zsh-users/zsh-completions \
        "$ZSH_CUSTOM/plugins/zsh-completions"
fi

echo "    Plugins instalados!"

# =============================================================================
# 4. COPIAR CONFIGS
# =============================================================================
echo ""
echo ">>> [4/6] Copiando arquivos de configuração..."

# .zshrc
cp "$DOTFILES_DIR/home/.zshrc" "$HOME/.zshrc"
echo "    .zshrc copiado!"

# kitty.conf
mkdir -p "$HOME/.config/kitty"
cp "$DOTFILES_DIR/home/.config/kitty/kitty.conf" "$HOME/.config/kitty/kitty.conf"
echo "    kitty.conf copiado!"

# starship.toml
mkdir -p "$HOME/.config"
cp "$DOTFILES_DIR/home/.config/starship.toml" "$HOME/.config/starship.toml"
echo "    starship.toml copiado!"

# fastfetch config
mkdir -p "$HOME/.config/fastfetch"
cp "$DOTFILES_DIR/home/.config/fastfetch/config.jsonc" "$HOME/.config/fastfetch/config.jsonc"
echo "  ✔ fastfetch config.jsonc copiado!"

# logo ASCII customizado
mkdir -p "$HOME/confifastfetch"
cp "$DOTFILES_DIR/home/confifastfetch/som.sh" "$HOME/confifastfetch/som.sh"
chmod +x "$HOME/confifastfetch/som.sh"
echo "  ✔ som.sh copiado!"

# =============================================================================
# 5. DEFINIR ZSH COMO SHELL PADRÃO
# =============================================================================
echo ""
echo ">>> [5/6] Definindo zsh como shell padrão..."

if [ "$SHELL" != "$(which zsh)" ]; then
    chsh -s "$(which zsh)"
    echo "    Shell alterado para zsh!"
else
    echo "    zsh já é o shell padrão!"
fi

# =============================================================================
# 6. FONTE NERD FONT (MesloLGM)
# =============================================================================
echo ""
echo ">>> [6/6] Verificando fonte MesloLGM Nerd Font..."

FONT_DIR="$HOME/.local/share/fonts"
mkdir -p "$FONT_DIR"

if ! fc-list | grep -qi "MesloLGM"; then
    echo "    Baixando MesloLGM Nerd Font..."
    FONT_URL="https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Meslo.zip"
    curl -Lo /tmp/Meslo.zip "$FONT_URL"
    unzip -o /tmp/Meslo.zip -d "$FONT_DIR" '*.ttf'
    rm /tmp/Meslo.zip
    fc-cache -fv > /dev/null
    echo "    Fonte instalada!"
else
    echo "    Fonte já está instalada!"
fi

# =============================================================================
# CONCLUÍDO
# =============================================================================
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║              Instalação concluída!  🎉               ║"
echo "║                                                      ║"
echo "║  Para aplicar as mudanças rode:                      ║"
echo "║    source ~/.zshrc   ou   exec zsh                   ║"
echo "║                                                      ║"
echo "║  Se o terminal pedir para trocar o shell,            ║"
echo "║  faça logout e login novamente.                      ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
