# ~/.config/starship.toml
scan_timeout = 1000  # em milissegundos (padrão é 30ms)

format = """
[│](bold green)[Computer](bold green)[ 💻 ](bold green) $directory$git_branch$git_status$python$nodejs
[└─>](bold green) $character"""

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold yellow"
format = "[$all_status$ahead_behind]($style) "

[python]
symbol = " "
style = "bold yellow"
format = "[$symbol$version]($style) "

[nodejs]
symbol = " "
style = "bold green"
format = "[$symbol$version]($style) "

[cmd_duration]
min_time = 500
style = "bold yellow"
format = "[$duration]($style) "

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

